### ISSUE TITLE
Include llama.cpp/common/common.h  in the bindings

### ISSUE THREAD

**Issue by aorticweb** [utilityai/llama-cpp-rs#114]
some [examples](https://github.com/ggerganov/llama.cpp/blob/master/examples/embedding/embedding.cpp) in the llama.cpp examples rely on function declared in the llama.cpp/common/common.h file,
would it be possible to add the function declared in that header file in the bindings?

**Comment by MarcusDunn** [comment]
I'd prefer not to, most of those can be fairly simply implemented in rust (the arg parsing I personally have implemented using clap every time I've needed it).

Is there a specific functionality that you are missing?
