### ISSUE TITLE
ggml_metal_init: ggm-common.h not found

### ISSUE THREAD

**Issue by Raphy42** [utilityai/llama-cpp-rs#211]
I updated to the latest version of the library, as I needed to have the `command-r` architecture support, but the curent `crates.io` and `main` version currently crash on MacOS due to `metal_hack` breaking in the latest version of `llama.cpp`
The culprit is `ggm-common.h` which is not avaiable to the bundled shader. I have tried replacing the `.h` by it's actual content, prior to putting it inside the `.m` loader, but it's not as simple and is not going to be maintainable at all.

```
ggml_metal_init: error: Error Domain=MTLLibraryErrorDomain Code=3 "program_source:3:10: fatal error: 'ggml-common.h' file not found
```
I saw on the llama.cpp issues that this could be fixed by having the `default.metallib` built by the CMake project, but this would imply modifying the current `build.rs` heavily, and I have no `CUDA` compatible machine.

**Comment by MarcusDunn** [comment]
https://github.com/utilityai/llama-cpp-rs/commit/756646ccffaca8049198d81ab184d56083f9162d

Did this commit not fix the issue?

Does it fail to compile or does it crash?

**Comment by Raphy42** [comment]
Sadly it doesn't, I'm currently messing around with my own public fork which uses `cmake` to build everything, which kinda works. (only a small problem of trying to allocate a 80G compute buffer).
But I think I might have broken all CUDA builds doing so ...

**Comment by MarcusDunn** [comment]
> Sadly it doesn't, I'm currently messing around with my own public fork which uses the cmake crate to build everything, which works !
I've been meaning to give this a try - I'd be happy to have a PR to this effect once it's ready. If you open a draft I can edit I can try to work on linux + cuda.

**Comment by Raphy42** [comment]
Sure ! Current edits are a bit _hacky_ but this is my current impl https://github.com/Raphy42/llama-cpp-rs/commit/44b6da48bb8d3522c51aa86eba2ded4096672777
I need to dig deeper in the llama.cpp build system in order to make the build.rs nicer and more parametric

**Comment by tinglou** [comment]
https://github.com/utilityai/llama-cpp-rs/pull/214

**Comment by MarcusDunn** [comment]
@Raphy42 does #221 fix it?

**Comment by MarcusDunn** [comment]
may be fixed on latest. Unable to test myself but #224 apparently fixes this, please let me know.

**Comment by Raphy42** [comment]
> @Raphy42 does #221 fix it? (no llama_hack, unsure if needed if using cmake)

Yeah, `"0.1.45"` works out of the box for me, tested on `gemma-7b` and multiple `llama-2` variants with the same inference speed from before !
Amazing job !

**Comment by MarcusDunn** [comment]
i just merged a PR. All credit to [derrickpersson](https://github.com/derrickpersson)!

Glad it works!
