### ISSUE TITLE
Do we have support for Vulkan ?

### ISSUE THREAD

**Issue by oddpxl** [utilityai/llama-cpp-rs#219]
I'm asking as I've just compiled my first Rust app for Android...

..and now curious to understand what it would take to compile it with llama-cpp-rs support for Android Vulkan :)
 
https://www.reddit.com/r/LocalLLaMA/comments/1adbzx8/as_of_about_4_minutes_ago_llamacpp_has_been/

**Comment by MarcusDunn** [comment]
No vulkan support at the moment.

I think the best bet is going to be using cmake to build `llama.cpp` - unfortunately adding an extra build time dep, but it simplfies maintenance a fair bit for all the platforms. See [#58](https://github.com/utilityai/llama-cpp-rs/issues/211) for an idea of what that would look like.

I will not be putting any effect this direction, all we use internally is linux + cuda so justifying work elsewhere is a tough sell. 

Contributions for vulkan are welcome though.

**Comment by oddpxl** [comment]
Does this mean llama-cpp-rs won't have Metal support going forward ?

llama-cpp-rs seems to be the fastest Rust LLM out there at the moment...Candle isn't even close :)

No worries I completely understand since your daily need is Cuda and not Metal / Vulkan / Other etc

**Comment by MarcusDunn** [comment]
https://github.com/utilityai/llama-cpp-rs/pull/202 I believe broke metal support which was in 0.1.42. (0.1.41 should be fine)

I expect metal support to be working once agin upon replacing `cc` with `cmake` in the `build.rs`, I'll take a stab at it sometime this week I think, but no promises :)

**Comment by MarcusDunn** [comment]
feel free to give #221 a try. No clue what the defaults for mac are (but a cursory glance makes me think it might *just work™)

**Comment by oddpxl** [comment]
I tried #221 and it first asked for libllama.dylib ( temp fix with some ructc compiler directive to set rpath ) ...then for ggml-metal.metal ( fixed that by copying it to the same folder ) ...then error: 'ggml-common.h' not found - back to square one :)

Unfortunately 0.1.41 don't compile either because of an old bug:

error[E0609]: no field `n_max_seq` on type `llama_kv_cache_view`
   --> /Users/odd/.cargo/registry/src/index.crates.io-6f17d22bba15001f/llama-cpp-2-0.1.41/src/context/kv_cache.rs:241:63

 usize::try_from(self.view.n_cells * self.view.n_max_seq)
                                                                          ^^^^^^^^^ unknown field
    
Perhaps --> usize::try_from(self.view.n_cells * self.view.n_seq_max)

( using this in my toml -->  llama-cpp-2 = "=0.1.41" )


..that said - many thanks for giving it a go - would be great with a version that works regardless of future metal support :)

**Comment by hazelnutcloud** [comment]
Is vulkan really not supported still? I see code to build for vulkan and some other backends in the build.rs of llama-cpp-sys. Wondering if thats usable at all.
