### ISSUE TITLE
Alternative for use of unstable library feature 'ptr_from_ref'

### ISSUE THREAD

**Issue by Jeadie** [utilityai/llama-cpp-rs#231]
Using `llama-cpp-2 = "0.1.45"` as a dependency requires using nightly rust for the unstable feature `'ptr_from_ref'`.

Example build error:
```
error[E0658]: use of unstable library feature 'ptr_from_ref'
   --> /Users/jeadie/.cargo/registry/src/index.crates.io-6f17d22bba15001f/llama-cpp-2-0.1.45/src/token/data_array.rs:362:22
    |
362 |         let mu_ptr = ptr::from_mut(mu);
    |                      ^^^^^^^^^^^^^
    |
    = note: see issue #106116 <https://github.com/rust-lang/rust/issues/106116> for more information
```

Is there any simple alternative for the underlying DataArray implementation? One alternative I have verified is at [Jeadie/llama-cpp-rs#c271be](https://github.com/Jeadie/llama-cpp-rs/commit/c271be61f3b6d9b7d440a4d6dc0efe4fed5f41cd).

**Comment by MarcusDunn** [comment]
I believe it's been stabilized, what version of rust are you using?

**Comment by Jeadie** [comment]
I think you are right. I am using `cargo 1.75.0`. The stablising [PR](https://github.com/rust-lang/rust/pull/117824) is in 1.76.1. Will verify.
