### ISSUE TITLE
Embeddings breaks on unknown strings

### ISSUE THREAD

**Issue by kinkel-ralf** [utilityai/llama-cpp-rs#249]
You can replicate the failure with this script after cloning into main.

cargo run --release --bin embeddings --package embeddings -- "The way to kill embeddings is giving tokens it can not convert back to string like தமிழ் తెలుగు for example." hf-model CompendiumLabs/bge-base-en-v1.5-gguf bge-base-en-v1.5-f16.gguf 

Output:
...
Prompt 0
 101 --> 
 1996 -->  the
 2126 -->  way
 2000 -->  to
 3102 -->  kill
 7861 -->  em
 8270 --> bed
 4667 --> ding
 2015 --> s
 2003 -->  is
 3228 -->  giving
 19204 -->  token
 2015 --> s
 2009 -->  it
 2064 -->  can
 2025 -->  not
 10463 -->  convert
 2067 -->  back
 2000 -->  to
 5164 -->  string
 2066 -->  like
 1385 -->  த
 29925 --> ம
Error: Unknown Token Type

**Comment by kinkel-ralf** [comment]
I fixed it locally but can't make a pull request as it's limited to collaborators.
I have it here if you want to have a look: [fix/handle_unk_tokens_emb](https://github.com/rachiki/llama-cpp-rs/tree/fix/handle_unk_tokens_emb)

**Comment by MarcusDunn** [comment]
You should be able to make PRs, did you fork the repo and make the PR from the fork?

**Comment by rachiki** [comment]
Sorry, I messed up the github accounts I was using, created the PR now

**Comment by MarcusDunn** [comment]
resolved in #250 thanks!
