### ISSUE TITLE
It seems LlamaTokenAttr should be a bitflags

### ISSUE THREAD

**Issue by estokes** [utilityai/llama-cpp-rs#350]
Running Phi3 with simple is failing with 

```
thread 'main' panicked at llama-cpp-2/src/model.rs:243:52:
token type is valid: UnknownValue(264)
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

Looking at the code it seems this token attr has both LLAMA_TOKEN_ATTR_CONTROL and LLAMA_TOKEN_ATTR_RSTRIP set. That seems like valid use in C, Perhaps LlamaTokenAttr should be migrated to an enumflags variant?

**Comment by MarcusDunn** [comment]
You're absolutely right, I've never done anything with bitflags in rust so expect a bit of a wait on this being fixed.

Thanks for the issue!

**Comment by estokes** [comment]
Oh, no worries, I'll fix it

**Comment by estokes** [comment]
I guess I should run by you, do you mind adding a dependency on enumflags2? That's a very nice library that I've used for this in the past, but it does pull in things like syn, etc for the proc macro support.

**Comment by MarcusDunn** [comment]
Yeah that should be fine, compile times are already pretty wild

**Comment by estokes** [comment]
added #351 which implements this
