### ISSUE TITLE
The latest version now is b3400. The rust binding is a month ago. Do you plan to update to the latest version?

### ISSUE THREAD

**Issue by SSFRPA** [utilityai/llama-cpp-rs#408]
The latest version now is b3400. The rust binding is a month ago. Do you plan to update to the latest version?

**Comment by MarcusDunn** [comment]
I'm aware and not thrilled about it.

There's a PR with up to date changes (mostly). It doesn't seem to be working on Mac at the moment and I don't have hardware to test it. You're welcome to pin your project to that branch for now if you're not on Mac, and if you are I'd love some testing!

**Comment by SSFRPA** [comment]
Thank you for your project. My system is windows, not mac. Unfortunately I cannot test mac, but I am also happy that a new version is available on windows.

**Comment by MarcusDunn** [comment]
the branch has been merged into main. Still somewhat behind but hopefully updates are a little smoother now that the llama.cpp dir structure is stable again.
