### ISSUE TITLE
crates.io publish jobs are failing even though it builds successfully (locally / for me)

### ISSUE THREAD

**Issue by babichjacob** [utilityai/llama-cpp-rs#518]
https://github.com/utilityai/llama-cpp-rs/actions/runs/10710926865/job/29698650066 failed

It claimed
>   CMake Error: The source directory "/home/runner/work/llama-cpp-rs/llama-cpp-rs/target/package/llama-cpp-sys-2-0.1.69/target/debug/build/llama-cpp-sys-2-d4132d04ad575bbe/out/llama.cpp" does not appear to contain CMakeLists.txt.

even though locally it is there. It's been a few weeks and there have been some changes. so maybe this was a fluke and it might just need to be attempted again? Though, the `version` specified in `llama-cpp-2` and `llama-cpp-sys-2` needs to be manually bumped because the job dedicated to it hasn't been doing it (#517) and 0.1.69 is already published. Possibly just fast forward to `0.1.80` as there are already GitHub releases up to `0.1.79`?

**Comment by babichjacob** [comment]
Oh, I see this was already noticed in https://github.com/utilityai/llama-cpp-rs/pull/489#issuecomment-2330307240
Let me see if contributing a pull request to solve it is within my capability...

**Comment by MarcusDunn** [comment]
that would be wonderful
