### ISSUE TITLE
Can't make this compile...

### ISSUE THREAD

**Issue by oddpxl** [utilityai/llama-cpp-rs#58]
Hey,

Really great to see this project - but unfortunately I can't seem to compile it - and this may well be may fault as I'm new at Rust.

( if so - my apologies )

Any advice or pointers would be much appreciated.

This is the error...   ( on a Macbookpro M1 MAX )

The following warnings were emitted during compilation:

warning: llama.cpp/ggml.c:2225:19: warning: unused function 'ggml_up32' [-Wunused-function]
warning: static inline int ggml_up32(int n) {
warning:                   ^
warning: llama.cpp/ggml.c:17941:13: warning: unused function 'ggml_opt_get_grad' [-Wunused-function]
warning: static void ggml_opt_get_grad(int np, struct ggml_tensor * const ps[], float * g) {
warning:             ^
warning: 2 warnings generated.
warning: llama.cpp/ggml-backend.c:1036:13: warning: unused function 'sched_print_assignments' [-Wunused-function]
warning: static void sched_print_assignments(ggml_backend_sched_t sched, struct ggml_cgraph * graph) {
warning:             ^
warning: 1 warning generated.
warning: llama.cpp/ggml-quants.c:1376:14: warning: unused function 'make_qkx1_quants' [-Wunused-function]
warning: static float make_qkx1_quants(int n, int nmax, const float * restrict x, uint8_t * restrict L, float * restrict the_min,
warning:              ^
warning: 1 warning generated.
warning: llama.cpp/llama.cpp:1179:34: error: use of undeclared identifier 'RLIMIT_MEMLOCK'
warning:         if (suggest && getrlimit(RLIMIT_MEMLOCK, &lock_limit)) {
warning:                                  ^
warning: 1 error generated.

error: failed to run custom build command for `llama-cpp-sys-2 v0.1.22`

Caused by:
  process didn't exit successfully: `/Users/odd/Documents/odd_LLM_rust/llamaload/target/release/build/llama-cpp-sys-2-db28f601b850efa8/build-script-build` (exit status: 1)
  --- stdout
  cargo:rerun-if-changed=llama.cpp
  compiling ggml
  TARGET = Some("aarch64-apple-darwin")
  OPT_LEVEL = Some("3")
  HOST = Some("aarch64-apple-darwin")
  cargo:rerun-if-env-changed=CC_aarch64-apple-darwin
  CC_aarch64-apple-darwin = None
  cargo:rerun-if-env-changed=CC_aarch64_apple_darwin
  CC_aarch64_apple_darwin = None
  cargo:rerun-if-env-changed=HOST_CC
  HOST_CC = None
  cargo:rerun-if-env-changed=CC
  CC = None
  cargo:rerun-if-env-changed=CRATE_CC_NO_DEFAULTS
  CRATE_CC_NO_DEFAULTS = None
  DEBUG = Some("false")
  CARGO_CFG_TARGET_FEATURE = Some("aes,crc,dit,dotprod,dpb,dpb2,fcma,fhm,flagm,fp16,frintts,jsconv,lor,lse,neon,paca,pacg,pan,pmuv3,ras,rcpc,rcpc2,rdm,sb,sha2,sha3,ssbs,vh")
  cargo:rerun-if-env-changed=CFLAGS_aarch64-apple-darwin
  CFLAGS_aarch64-apple-darwin = None
  cargo:rerun-if-env-changed=CFLAGS_aarch64_apple_darwin
  CFLAGS_aarch64_apple_darwin = None
  cargo:rerun-if-env-changed=HOST_CFLAGS
  HOST_CFLAGS = None
  cargo:rerun-if-env-changed=CFLAGS
  CFLAGS = None
  running: env -u IPHONEOS_DEPLOYMENT_TARGET "cc" "-O3" "-ffunction-sections" "-fdata-sections" "-fPIC" "-arch" "arm64" "-std=c17" "-Wall" "-Wextra" "-DGGML_USE_K_QUANTS" "-o" "/Users/odd/Documents/odd_LLM_rust/llamaload/target/release/build/llama-cpp-sys-2-809516a64fd910ba/out/llama.cpp/ggml.o" "-c" "llama.cpp/ggml.c"
  cargo:warning=llama.cpp/ggml.c:2225:19: warning: unused function 'ggml_up32' [-Wunused-function]

  cargo:warning=static inline int ggml_up32(int n) {

  cargo:warning=                  ^

  cargo:warning=llama.cpp/ggml.c:17941:13: warning: unused function 'ggml_opt_get_grad' [-Wunused-function]

  cargo:warning=static void ggml_opt_get_grad(int np, struct ggml_tensor * const ps[], float * g) {

  cargo:warning=            ^

  cargo:warning=2 warnings generated.

  exit status: 0
  running: env -u IPHONEOS_DEPLOYMENT_TARGET "cc" "-O3" "-ffunction-sections" "-fdata-sections" "-fPIC" "-arch" "arm64" "-std=c17" "-Wall" "-Wextra" "-DGGML_USE_K_QUANTS" "-o" "/Users/odd/Documents/odd_LLM_rust/llamaload/target/release/build/llama-cpp-sys-2-809516a64fd910ba/out/llama.cpp/ggml-alloc.o" "-c" "llama.cpp/ggml-alloc.c"
  exit status: 0
  running: env -u IPHONEOS_DEPLOYMENT_TARGET "cc" "-O3" "-ffunction-sections" "-fdata-sections" "-fPIC" "-arch" "arm64" "-std=c17" "-Wall" "-Wextra" "-DGGML_USE_K_QUANTS" "-o" "/Users/odd/Documents/odd_LLM_rust/llamaload/target/release/build/llama-cpp-sys-2-809516a64fd910ba/out/llama.cpp/ggml-backend.o" "-c" "llama.cpp/ggml-backend.c"
  cargo:warning=llama.cpp/ggml-backend.c:1036:13: warning: unused function 'sched_print_assignments' [-Wunused-function]

  cargo:warning=static void sched_print_assignments(ggml_backend_sched_t sched, struct ggml_cgraph * graph) {

  cargo:warning=            ^

  cargo:warning=1 warning generated.

  exit status: 0
  running: env -u IPHONEOS_DEPLOYMENT_TARGET "cc" "-O3" "-ffunction-sections" "-fdata-sections" "-fPIC" "-arch" "arm64" "-std=c17" "-Wall" "-Wextra" "-DGGML_USE_K_QUANTS" "-o" "/Users/odd/Documents/odd_LLM_rust/llamaload/target/release/build/llama-cpp-sys-2-809516a64fd910ba/out/llama.cpp/ggml-quants.o" "-c" "llama.cpp/ggml-quants.c"
  cargo:warning=llama.cpp/ggml-quants.c:1376:14: warning: unused function 'make_qkx1_quants' [-Wunused-function]

  cargo:warning=static float make_qkx1_quants(int n, int nmax, const float * restrict x, uint8_t * restrict L, float * restrict the_min,

  cargo:warning=             ^

  cargo:warning=1 warning generated.

  exit status: 0
  cargo:rerun-if-env-changed=AR_aarch64-apple-darwin
  AR_aarch64-apple-darwin = None
  cargo:rerun-if-env-changed=AR_aarch64_apple_darwin
  AR_aarch64_apple_darwin = None
  cargo:rerun-if-env-changed=HOST_AR
  HOST_AR = None
  cargo:rerun-if-env-changed=AR
  AR = None
  cargo:rerun-if-env-changed=ARFLAGS_aarch64-apple-darwin
  ARFLAGS_aarch64-apple-darwin = None
  cargo:rerun-if-env-changed=ARFLAGS_aarch64_apple_darwin
  ARFLAGS_aarch64_apple_darwin = None
  cargo:rerun-if-env-changed=HOST_ARFLAGS
  HOST_ARFLAGS = None
  cargo:rerun-if-env-changed=ARFLAGS
  ARFLAGS = None
  running: ZERO_AR_DATE="1" "ar" "cq" "/Users/odd/Documents/odd_LLM_rust/llamaload/target/release/build/llama-cpp-sys-2-809516a64fd910ba/out/libggml.a" "/Users/odd/Documents/odd_LLM_rust/llamaload/target/release/build/llama-cpp-sys-2-809516a64fd910ba/out/llama.cpp/ggml.o" "/Users/odd/Documents/odd_LLM_rust/llamaload/target/release/build/llama-cpp-sys-2-809516a64fd910ba/out/llama.cpp/ggml-alloc.o" "/Users/odd/Documents/odd_LLM_rust/llamaload/target/release/build/llama-cpp-sys-2-809516a64fd910ba/out/llama.cpp/ggml-backend.o" "/Users/odd/Documents/odd_LLM_rust/llamaload/target/release/build/llama-cpp-sys-2-809516a64fd910ba/out/llama.cpp/ggml-quants.o"
  exit status: 0
  running: "ar" "s" "/Users/odd/Documents/odd_LLM_rust/llamaload/target/release/build/llama-cpp-sys-2-809516a64fd910ba/out/libggml.a"
  exit status: 0
  cargo:rustc-link-lib=static=ggml
  cargo:rustc-link-search=native=/Users/odd/Documents/odd_LLM_rust/llamaload/target/release/build/llama-cpp-sys-2-809516a64fd910ba/out
  compiling llama
  TARGET = Some("aarch64-apple-darwin")
  OPT_LEVEL = Some("3")
  HOST = Some("aarch64-apple-darwin")
  cargo:rerun-if-env-changed=CXX_aarch64-apple-darwin
  CXX_aarch64-apple-darwin = None
  cargo:rerun-if-env-changed=CXX_aarch64_apple_darwin
  CXX_aarch64_apple_darwin = None
  cargo:rerun-if-env-changed=HOST_CXX
  HOST_CXX = None
  cargo:rerun-if-env-changed=CXX
  CXX = None
  cargo:rerun-if-env-changed=CRATE_CC_NO_DEFAULTS
  CRATE_CC_NO_DEFAULTS = None
  DEBUG = Some("false")
  CARGO_CFG_TARGET_FEATURE = Some("aes,crc,dit,dotprod,dpb,dpb2,fcma,fhm,flagm,fp16,frintts,jsconv,lor,lse,neon,paca,pacg,pan,pmuv3,ras,rcpc,rcpc2,rdm,sb,sha2,sha3,ssbs,vh")
  cargo:rerun-if-env-changed=CXXFLAGS_aarch64-apple-darwin
  CXXFLAGS_aarch64-apple-darwin = None
  cargo:rerun-if-env-changed=CXXFLAGS_aarch64_apple_darwin
  CXXFLAGS_aarch64_apple_darwin = None
  cargo:rerun-if-env-changed=HOST_CXXFLAGS
  HOST_CXXFLAGS = None
  cargo:rerun-if-env-changed=CXXFLAGS
  CXXFLAGS = None
  running: env -u IPHONEOS_DEPLOYMENT_TARGET "c++" "-O3" "-ffunction-sections" "-fdata-sections" "-fPIC" "-arch" "arm64" "-std=c++17" "-Wall" "-Wextra" "-D_XOPEN_SOURCE=600" "-o" "/Users/odd/Documents/odd_LLM_rust/llamaload/target/release/build/llama-cpp-sys-2-809516a64fd910ba/out/llama.cpp/llama.o" "-c" "llama.cpp/llama.cpp"
  cargo:warning=llama.cpp/llama.cpp:1179:34: error: use of undeclared identifier 'RLIMIT_MEMLOCK'

  cargo:warning=        if (suggest && getrlimit(RLIMIT_MEMLOCK, &lock_limit)) {

  cargo:warning=                                 ^

  cargo:warning=1 error generated.

  exit status: 1

  --- stderr

  error occurred: Command env -u IPHONEOS_DEPLOYMENT_TARGET "c++" "-O3" "-ffunction-sections" "-fdata-sections" "-fPIC" "-arch" "arm64" "-std=c++17" "-Wall" "-Wextra" "-D_XOPEN_SOURCE=600" "-o" 

"/Users/odd/Documents/odd_LLM_rust/llamaload/target/release/build/llama-cpp-sys-2-809516a64fd910ba/out/llama.cpp/llama.o" "-c" "llama.cpp/llama.cpp" with args "c++" did not execute successfully (status code exit status: 1).

**Comment by MarcusDunn** [comment]
I haven't tested this on mac - its very likely this is an bug. I'll take a look into it tonight when I've got access to a mac. 

I *think* it's going to be an issue with the fact [this](https://github.com/ggerganov/llama.cpp/blob/191221178f51b6e81122c5bda0fd79620e547d07/Makefile#L133-L141) logic is not implemented in `build.rs`, if you want to take a stab at fixing it yourself feel free!

**Comment by MarcusDunn** [comment]
definitely an issue on our end :+1:  https://github.com/utilityai/llama-cpp-rs/actions/runs/7760630033/job/21167298611
